// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domains "github.com/Kosk0l/TgBotConverter/internal/domains"
	mock "github.com/stretchr/testify/mock"
)

// DialogRepository is an autogenerated mock type for the DialogRepository type
type DialogRepository struct {
	mock.Mock
}

// DeleteStateRepo provides a mock function with given fields: ctx, chatId
func (_m *DialogRepository) DeleteStateRepo(ctx context.Context, chatId int64) error {
	ret := _m.Called(ctx, chatId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStateRepo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, chatId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStateRepo provides a mock function with given fields: ctx, chatId
func (_m *DialogRepository) GetStateRepo(ctx context.Context, chatId int64) (domains.State, error) {
	ret := _m.Called(ctx, chatId)

	if len(ret) == 0 {
		panic("no return value specified for GetStateRepo")
	}

	var r0 domains.State
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domains.State, error)); ok {
		return rf(ctx, chatId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domains.State); ok {
		r0 = rf(ctx, chatId)
	} else {
		r0 = ret.Get(0).(domains.State)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetStateRepo provides a mock function with given fields: ctx, state
func (_m *DialogRepository) SetStateRepo(ctx context.Context, state domains.State) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for SetStateRepo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domains.State) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDialogRepository creates a new instance of DialogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DialogRepository {
	mock := &DialogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
