// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domains "github.com/Kosk0l/TgBotConverter/internal/domains"

	mock "github.com/stretchr/testify/mock"
)

// JobRepository is an autogenerated mock type for the JobRepository type
type JobRepository struct {
	mock.Mock
}

// DeleteKey provides a mock function with given fields: ctx, jobId
func (_m *JobRepository) DeleteKey(ctx context.Context, jobId string) error {
	ret := _m.Called(ctx, jobId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFromHash provides a mock function with given fields: ctx, jobId
func (_m *JobRepository) GetFromHash(ctx context.Context, jobId string) (domains.Job, error) {
	ret := _m.Called(ctx, jobId)

	if len(ret) == 0 {
		panic("no return value specified for GetFromHash")
	}

	var r0 domains.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domains.Job, error)); ok {
		return rf(ctx, jobId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domains.Job); ok {
		r0 = rf(ctx, jobId)
	} else {
		r0 = ret.Get(0).(domains.Job)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFromList provides a mock function with given fields: ctx
func (_m *JobRepository) GetFromList(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFromList")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetToHash provides a mock function with given fields: ctx, job
func (_m *JobRepository) SetToHash(ctx context.Context, job domains.Job) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for SetToHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domains.Job) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetToList provides a mock function with given fields: ctx, jobId
func (_m *JobRepository) SetToList(ctx context.Context, jobId string) error {
	ret := _m.Called(ctx, jobId)

	if len(ret) == 0 {
		panic("no return value specified for SetToList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJobRepository creates a new instance of JobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRepository {
	mock := &JobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
